language: java
dist: xenial
sudo: required
jdk:
- openjdk11
git:
    depth: 3
env: > 
      MAVEN_OPTS="-Xms1g -Xmx2g" 

before_script:
- export TZ=Canada/Eastern

script:
  - mvn clean install -DskipITs=false

cache:
    directories:
    - "$HOME/.m2"
