language: java
dist: trusty
sudo: required
jdk:
- oraclejdk7
git:
    depth: 3
env: > 
      MAVEN_SETTINGS="${TRAVIS_BUILD_DIR}/gsi-config"
      MAVEN_OPTS="-Xms1g -Xmx2g" 
addons:
    sonarcloud:
        organization: "oicr-gsi"
        token:
            secure: "Oy9FmBHP4VqRHBIHLdN2kwWJvWdctRHn6pDYJhqCuxP9f80RCAOFkiaq3jJEUhm3HH2vx96QuHApXDTl3jSbtxIYEJ4+A5Ufgki3cGgWi2C5ucze4VfFM/YddF3EzR7I50rDRqQdcTqPFkqwv/md5jF7xTQ7SotSYQKqV3SscPtZV0ySXuDK4nojuIKVM0+h5Qx2fBxoFcgGewmxFr/UL872TNJwsoffHG2a0tNkGm09PseaDXc1QWr46VwRBP8xOUIDJeBwIb5C3Ok50Y5un5zsq7aTOFBXHICfJkSSzzcp/E8ZZIZnSgPy6pQ1pyMKr74F48o8LkuOvsxRQb8x/jFwb/bbHyQzETWRd4bplPIkfHEZ+ykStobAmDMYxQgG3W7qIkBiwW1c4vWTnr8VTKGLgj6Skyl74OwJSoKoc1ilxEYqShkPJlLnp+akIFTVqOhUX/qMn81HgOeXD5nEdRUwtc8CFEZCVfe28SfIcgOnJv2uBTrLCI495GCw/FDtIcf284iwyVBkPEREIwCpvjkEWKVLh3kvEd0/jT/RGoci2GkPHvnIVoj3ttV6p8qvHTMT06/FPGEkY5Vjl6EwemWVIiJye7QJVDhnjmcf7LPxD5tO/Bx4RebFQzxlrdo6WuAsxCiT3Im1nnyBDRGLyO5ThVyAyaxwaQkqGTm3Af8="
        github_token:
            secure: "vU2Y5K9WIe/iHIyeGDwboVWDCAPTK1qluU9XzRd/x1TAZAPFsitOEQQgWeEnBlSjbeSNsFeDbO001hPY7Z25r4wR0VNi7SobQ/ePfvtcDiSrJJxEyH0V+2QBQoxMt/lA4AmT4xWE/8eyfuBXTfx+tWmw4b2KDfcZ4YULlr1lose2c3It9yNo9Cb1C5LuCA1m9+hQZPc+YrK+O9Gou5c7k37BPntYEuaU2QSWJs3m4/6IGBCJyzfbKI0dpVyxQvLJQvxGS5WqLec/gGkde5aMTWl2bMfQpq16IOVb4nynPM3Hb8K7BppnhbzyctTuMXsPyPdJdXILqYykX4eh29iKALNLExq90K8OszNK1bUWQYfi4e8s2QfP0wFYxFPEXJQtSRfBSF6YtlwBdbZgyhBgA+/3tI/OOvZMcKi/wf55iXrhDjTf3IQMozFCHEJ5OyUxMak/Q0YZgEk9vRpireR8X5SYAcwoKP6aHZjA9v8OIBGSwPlXcd2XlKOdrfPuw/JrglAFHUYcG787xc6nJmSYy7QXgFL/n36Ga+rCUYwEs2xlHM6ppopJG0kWCd8BwUfTK0Q3/gq9DMAXH+1oXQ03pKCtJ7zL5pc7CI5vO93h8rIQVovbtarYsyZEVB571V9BHaiEe/DCZIChRUcGnjaBNOR8JIYVAQAc6hDnOVpvZuQ="

before_install:
- git clone https://github.com/oicr-gsi/gsi-config.git "${MAVEN_SETTINGS}"
- cp "${MAVEN_SETTINGS}/settings.xml" "${HOME}/.m2/settings.xml"
- jdk_switcher use oraclejdk7
- jdk_switcher home oraclejdk7

before_script:
- export TZ=EST

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
    directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
